name: Build Child Theme Release

# Geef write-permissions zodat releases aangemaakt kunnen worden
permissions:
  contents: write
  packages: write

# Trigger de workflow bij een tag push
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout de repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Maak de ZIP van de theme
      - name: Create ZIP
        run: |
          mkdir build
          rsync -av --exclude='.git*' ./ build/herenboeren-hello-child
          cd build
          zip -r herenboeren-hello-child.zip herenboeren-hello-child

      # Upload ZIP naar GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/herenboeren-hello-child.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}